/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mutia.view;

import mutia.controller.PengembalianController;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author LABSIDOSEN
 */
public class FormPengembalian extends javax.swing.JFrame {

    /**
     * Creates new form FormPengembalian
     */
    private PengembalianController controller;
    public FormPengembalian() {
        initComponents();
        controller = new PengembalianController(this);
        controller.bersihForm();
    }

    public JComboBox<String> getCboAnggota() {
        return cboAnggota;
    }

    public JComboBox<String> getCboBuku() {
        return cboBuku;
    }

    public JTextField getTxtDenda() {
        return txtDenda;
    }

    public JTextField getTxtTerlambat() {
        return txtTerlambat;
    }

    public JTextField getTxtTglDikembalikan() {
        return txtTglDikembalikan;
    }

    public JTextField getTxtTglKembali() {
        return txtTglKembali;
    }

    public JTextField getTxtTglPinjam() {
        return txtTglPinjam;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboAnggota = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboBuku = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtTglPinjam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTglKembali = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTglDikembalikan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTerlambat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDenda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Kode Anggota");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 100, 16);

        cboAnggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboAnggota);
        cboAnggota.setBounds(150, 20, 370, 30);

        jLabel2.setText("Buku");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 120, 16);

        cboBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboBuku);
        cboBuku.setBounds(150, 50, 370, 30);

        jLabel3.setText("Tgl Pinjam");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 110, 16);

        txtTglPinjam.setText("jTextField1");
        getContentPane().add(txtTglPinjam);
        txtTglPinjam.setBounds(150, 80, 370, 30);

        jLabel4.setText("Tgl Kembali");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 130, 16);

        txtTglKembali.setText("jTextField2");
        getContentPane().add(txtTglKembali);
        txtTglKembali.setBounds(150, 110, 370, 30);

        jLabel5.setText("Tgl Dikembalikan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 120, 16);

        txtTglDikembalikan.setText("jTextField3");
        getContentPane().add(txtTglDikembalikan);
        txtTglDikembalikan.setBounds(150, 140, 370, 30);

        jLabel6.setText("Terlambat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 170, 110, 16);

        txtTerlambat.setText("jTextField4");
        getContentPane().add(txtTerlambat);
        txtTerlambat.setBounds(150, 170, 370, 30);

        jLabel7.setText("Denda");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 200, 120, 16);

        txtDenda.setText("jTextField5");
        getContentPane().add(txtDenda);
        txtDenda.setBounds(150, 200, 370, 30);

        jButton1.setText("insert");
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 250, 90, 30);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 250, 90, 30);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 250, 90, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd Anggota", "Nama", "Kd Buku", "Tgl Pinjam", "Tgl Kembali", "Dikembalikan", "Terlambat", "Denda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 292, 600, 330);

        jButton4.setText("Cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(530, 80, 80, 30);

        jButton5.setText("Proses");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(530, 140, 80, 30);

        setSize(new java.awt.Dimension(658, 677));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        controller.searchPinjam();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        controller.proses();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboAnggota;
    private javax.swing.JComboBox<String> cboBuku;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtTerlambat;
    private javax.swing.JTextField txtTglDikembalikan;
    private javax.swing.JTextField txtTglKembali;
    private javax.swing.JTextField txtTglPinjam;
    // End of variables declaration//GEN-END:variables
}
