/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cobaCoba8525;

/**
 *
 * @author user
 */
public class FormStudent extends javax.swing.JFrame {

    /**
     * Creates new form FormStudent
     */
    public FormStudent() {
        initComponents();
        this.clearForm();
    }
    
    public void clearForm(){
        txtNama.setText("");
        txtAlamat.setText("");
        txtUmur.setText("");
        txtMatematika.setText("");
        txtBhs_Inggris.setText("");
        txtIlmu_Pengetahuan.setText("");
        txtRata_rata.setText("");   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUmur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMatematika = new javax.swing.JTextField();
        txtBhs_Inggris = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIlmu_Pengetahuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRata_rata = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 60, 16);

        txtNama.setText("jTextField1");
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama);
        txtNama.setBounds(120, 10, 260, 22);

        jLabel2.setText("Alamat");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 60, 16);

        txtAlamat.setText("jTextField2");
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(120, 40, 260, 22);

        jLabel3.setText("Umur");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 60, 16);

        txtUmur.setText("jTextField3");
        getContentPane().add(txtUmur);
        txtUmur.setBounds(120, 70, 260, 22);

        jLabel4.setText("Matematika");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 62, 16);

        jLabel5.setText("Bhs Inggris");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 60, 16);

        txtMatematika.setText("jTextField4");
        getContentPane().add(txtMatematika);
        txtMatematika.setBounds(120, 100, 260, 22);

        txtBhs_Inggris.setText("jTextField5");
        getContentPane().add(txtBhs_Inggris);
        txtBhs_Inggris.setBounds(120, 130, 260, 22);

        jLabel6.setText("Ilmu Pengetahuan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 160, 95, 16);

        txtIlmu_Pengetahuan.setText("jTextField6");
        getContentPane().add(txtIlmu_Pengetahuan);
        txtIlmu_Pengetahuan.setBounds(120, 160, 260, 22);

        jLabel7.setText("Rata-rata");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 240, 90, 16);

        txtRata_rata.setText("jTextField7");
        getContentPane().add(txtRata_rata);
        txtRata_rata.setBounds(120, 240, 260, 22);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(10, 200, 370, 23);

        setSize(new java.awt.Dimension(413, 286));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        StudentRecord oom = new StudentRecord();
        
        oom.setName(txtNama.getText());
        oom.setAddress(txtAlamat.getText());
        oom.setAge(Integer.parseInt (txtUmur.getText()));
        oom.setMathGrade(Double.parseDouble (txtMatematika.getText()));
        oom.setEnglishGrade(Double.parseDouble (txtBhs_Inggris.getText()));
        oom.setScienceGrade(Double.parseDouble (txtIlmu_Pengetahuan.getText()));
        txtRata_rata.setText(String.valueOf(oom.getAverage()));
        
        
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBhs_Inggris;
    private javax.swing.JTextField txtIlmu_Pengetahuan;
    private javax.swing.JTextField txtMatematika;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtRata_rata;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
